// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"context"
)

type Querier interface {
	FindRegisteredEmail(ctx context.Context, email string) (AuthenticationUser, error)
}

var _ Querier = (*Queries)(nil)
