// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package repository

import (
	"context"
)

const findRegisteredEmail = `-- name: FindRegisteredEmail :one
SELECT email, password FROM authentication.users
    WHERE users.email= ?
        LIMIT 1
`

func (q *Queries) FindRegisteredEmail(ctx context.Context, email string) (AuthenticationUser, error) {
	row := q.db.QueryRowContext(ctx, findRegisteredEmail, email)
	var i AuthenticationUser
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}
