// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package repository

import (
	"context"
)

const findRegisteredEmail = `-- name: FindRegisteredEmail :one
SELECT email FROM authentication.users
    WHERE users.email= @email
    LIMIT 1
`

func (q *Queries) FindRegisteredEmail(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, findRegisteredEmail)
	var email string
	err := row.Scan(&email)
	return email, err
}
