apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: general-resources-application
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/Archisman-Mridha/twitter-clone
        targetRevision: HEAD
        path: kubernetes/general-resources
        directory:
            recurse: true

    destination:
        server: https://kubernetes.default.svc
        namespace: argocd

    syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true