// Code generated by MockGen. DO NOT EDIT.
// Source: repository/querier.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	repository "authentication/repository"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// FindRegisteredEmail mocks base method.
func (m *MockQuerier) FindRegisteredEmail(ctx context.Context, email string) (repository.AuthenticationUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRegisteredEmail", ctx, email)
	ret0, _ := ret[0].(repository.AuthenticationUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRegisteredEmail indicates an expected call of FindRegisteredEmail.
func (mr *MockQuerierMockRecorder) FindRegisteredEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRegisteredEmail", reflect.TypeOf((*MockQuerier)(nil).FindRegisteredEmail), ctx, email)
}
